---
crds_prometheus_operator_helm_chart_ref: /charts/prometheus-operator-crds
crds_prometheus_operator_helm_release_name: prometheus-operator-crds
crds_prometheus_operator_helm_release_namespace: prometheus-operator-crds
crds_prometheus_operator_helm_values: {}

crds_yaook_operators_helm_chart_ref: /charts/crds
crds_yaook_operators_helm_release_name: yaook-operators-crds
crds_yaook_operators_helm_release_namespace: yaook-operators-crds
crds_yaook_operators_helm_values: {}
